export const TODOS_LOS_MESES = [
  'ENERO',
  'FEBRERO',
  'MARZO',
  'ABRIL',
  'MAYO',
  'JUNIO',
  'JULIO',
  'AGOSTO',
  'SEPTIEMBRE',
  'OCTUBRE',
  'NOVIEMBRE',
  'DICIEMBRE'
];

export const VALOR_MES = {
  ENERO: 10000,
  FEBRERO: 10000,
  MARZO: 5000,
  ABRIL: 5000,
  MAYO: 8000,
  JUNIO: 8000,
  JULIO: 8000,
  AGOSTO: 8000,
  SEPTIEMBRE: 8000,
  OCTUBRE: 8000,
  NOVIEMBRE: 8000,
  DICIEMBRE: 8000
};

export const CAMPOS_CORTA_FUEGO = [
  'CORTA FUEGO',
  'FUEGO',
  'CORTA\nFUEGO',
  'CORTAFUEGO',
  'CORTA  FUEGO',
  'CORTA-FUEGO',
  'CORTA_FUEGO',
  'CORTA F',
  'CUOTA EXTRA',
  'EXTRA',
  'CORTA',
  'CORTA FUEGO ',
  ' CORTA FUEGO',
  'CORTA FUEGO CLP'
];
